/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Model.RoundBorder;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author lorente
 */
public class V_Menu extends javax.swing.JFrame {

    /**
     * Creates new form V_Menu
     */
    public V_Menu() {
        initComponents();
        jButton_8x9.setBackground(Color.gray);
        jButton_8x9.setBorder(new RoundBorder(10));
        jButton_16x16.setBackground(Color.gray);
        jButton_16x16.setBorder(new RoundBorder(10));
        jButton_30x16.setBackground(Color.gray);
        jButton_30x16.setBorder(new RoundBorder(10));
        jButton_Personalitzat.setBackground(Color.gray);
        jButton_Personalitzat.setBorder(new RoundBorder(10));
        this.getContentPane().setBackground(Color.DARK_GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_16x16 = new javax.swing.JButton();
        jButton_8x9 = new javax.swing.JButton();
        jButton_30x16 = new javax.swing.JButton();
        jButton_Personalitzat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jButton_16x16.setFont(new java.awt.Font("Dyuthi", 0, 24)); // NOI18N
        jButton_16x16.setForeground(new java.awt.Color(255, 255, 255));
        jButton_16x16.setText("<html><center><p>16 x 16</p><p><font size=\"5\">40 mines</font></p></center></html>");
        jButton_16x16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 63, 65), 1, true));
        jButton_16x16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_16x16ActionPerformed(evt);
            }
        });

        jButton_8x9.setFont(new java.awt.Font("Dyuthi", 0, 24)); // NOI18N
        jButton_8x9.setForeground(new java.awt.Color(255, 255, 255));
        jButton_8x9.setText("<html><center><p>8 x 8</p></center><p><font size=\"5\">10 mines</font></p></html>"); // NOI18N
        jButton_8x9.setToolTipText("");
        jButton_8x9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 63, 65), 1, true));
        jButton_8x9.setFocusPainted(false);
        jButton_8x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8x9ActionPerformed(evt);
            }
        });

        jButton_30x16.setFont(new java.awt.Font("Dyuthi", 0, 24)); // NOI18N
        jButton_30x16.setForeground(new java.awt.Color(255, 255, 255));
        jButton_30x16.setText("<html><center><p>30 x 16</p><p><font size=\"5\">99 mines</font></p></center></html>");
        jButton_30x16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 63, 65), 1, true));
        jButton_30x16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_30x16ActionPerformed(evt);
            }
        });

        jButton_Personalitzat.setFont(new java.awt.Font("Dyuthi", 0, 24)); // NOI18N
        jButton_Personalitzat.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Personalitzat.setText("<html><center><p>?</p><p><font size=\"5\">Personalitzat</font></p></center></html>");
        jButton_Personalitzat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 63, 65), 1, true));
        jButton_Personalitzat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PersonalitzatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_8x9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_16x16, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_30x16, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Personalitzat, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton_16x16, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_8x9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_30x16, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Personalitzat, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_16x16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_16x16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_16x16ActionPerformed

    private void jButton_8x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8x9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_8x9ActionPerformed

    private void jButton_30x16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_30x16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_30x16ActionPerformed

    private void jButton_PersonalitzatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PersonalitzatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PersonalitzatActionPerformed

    public JButton getjButton_16x16() {

        return jButton_16x16;
    }

    public void setjButton_16x16(JButton jButton_16x16) {
        this.jButton_16x16 = jButton_16x16;
    }

    public JButton getjButton_30x16() {
        return jButton_30x16;
    }

    public void setjButton_30x16(JButton jButton_30x16) {
        this.jButton_30x16 = jButton_30x16;
    }

    public JButton getjButton_8x9() {
        return jButton_8x9;
    }

    public void setjButton_8x9(JButton jButton_8x9) {
        this.jButton_8x9 = jButton_8x9;
    }

    public JButton getjButton_Personalitzat() {
        return jButton_Personalitzat;
    }

    public void setjButton_Personalitzat(JButton jButton_Personalitzat) {
        this.jButton_Personalitzat = jButton_Personalitzat;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_16x16;
    private javax.swing.JButton jButton_30x16;
    private javax.swing.JButton jButton_8x9;
    private javax.swing.JButton jButton_Personalitzat;
    // End of variables declaration//GEN-END:variables
}
