/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Panel;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author lorente
 */
public class V_Tauler extends javax.swing.JFrame {

    /**
     * Creates new form V_Tauler
     */
    public V_Tauler() {

        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        jButton_Puntu.setBackground(Color.gray);
        jButton_Diff.setBackground(Color.gray);
        jButton_Sortir.setBackground(Color.gray);
        jButton_Pause.setBackground(Color.gray);
        jButton_Restart.setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tauler = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jlabel_minas = new javax.swing.JLabel();
        jlabel_contador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_temps = new javax.swing.JLabel();
        jButton_Puntu = new javax.swing.JButton();
        jButton_Diff = new javax.swing.JButton();
        jButton_Sortir = new javax.swing.JButton();
        jButton_Pause = new javax.swing.JButton();
        jButton_Restart = new javax.swing.JButton();

        panel_tauler.setBackground(new java.awt.Color(51, 51, 51));
        panel_tauler.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panel_taulerLayout = new javax.swing.GroupLayout(panel_tauler);
        panel_tauler.setLayout(panel_taulerLayout);
        panel_taulerLayout.setHorizontalGroup(
            panel_taulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        panel_taulerLayout.setVerticalGroup(
            panel_taulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jlabel_minas.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_minas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlabel_contador.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_contador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlabel_contador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_temps.setForeground(new java.awt.Color(255, 255, 255));

        jButton_Puntu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Puntu.setText("Puntuacio");

        jButton_Diff.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Diff.setText("Dificultat");

        jButton_Sortir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Sortir.setText("Sortir");

        jButton_Pause.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Pause.setText("Pausar");

        jButton_Restart.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Restart.setText("Restart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_tauler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_temps, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlabel_contador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabel_minas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_Puntu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Diff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Sortir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Pause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_tauler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel_contador, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_minas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_temps, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Sortir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Diff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Puntu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Pause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Restart)
                .addGap(53, 53, 53))
        );

        panel_tauler.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Tauler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Tauler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Tauler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Tauler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Tauler().setVisible(true);
            }
        });
    }

    public JButton getjButton_Restart() {
        return jButton_Restart;
    }

    public void setjButton_Restart(JButton jButton_Restart) {
        this.jButton_Restart = jButton_Restart;
    }

    public JButton getjButton_Pause() {
        return jButton_Pause;
    }

    public void setjButton_Pause(JButton jButton_Pause) {
        this.jButton_Pause = jButton_Pause;
    }

    public JButton getjButton_Sortir() {
        return jButton_Sortir;
    }

    public void setjButton_Sortir(JButton jButton_Sortir) {
        this.jButton_Sortir = jButton_Sortir;
    }

    public JButton getjButton_Diff() {
        return jButton_Diff;
    }

    public void setjButton_Diff(JButton jButton_Diff) {
        this.jButton_Diff = jButton_Diff;
    }

    public JButton getjButton_Puntu() {
        return jButton_Puntu;
    }

    public void setjButton_Puntu(JButton jButton_Puntu) {
        this.jButton_Puntu = jButton_Puntu;
    }

    public Panel getPanel_tauler() {
        return panel_tauler;
    }

    public void setPanel_tauler(Panel panel_tauler) {
        this.panel_tauler = panel_tauler;
    }

    public void agregarBoton(javax.swing.JButton boton) {
        panel_tauler.add(boton);
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getJlabel_contador() {
        return jlabel_contador;
    }

    public void setJlabel_contador(JLabel jlabel_contador) {
        this.jlabel_contador = jlabel_contador;
    }

    public JLabel getJlabel_minas() {
        return jlabel_minas;
    }

    public void setJlabel_minas(JLabel jlabel_minas) {
        this.jlabel_minas = jlabel_minas;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel_temps() {
        return jLabel_temps;
    }

    public void setjLabel_temps(JLabel jLabel_temps) {
        this.jLabel_temps = jLabel_temps;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Diff;
    private javax.swing.JButton jButton_Pause;
    private javax.swing.JButton jButton_Puntu;
    private javax.swing.JButton jButton_Restart;
    private javax.swing.JButton jButton_Sortir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_temps;
    private javax.swing.JLabel jlabel_contador;
    private javax.swing.JLabel jlabel_minas;
    private java.awt.Panel panel_tauler;
    // End of variables declaration//GEN-END:variables
}
